from .QQEventHandler import QQEventHandler
from .QQGroupEventHandler import QQGroupEventHandler

commands = {
  "/cat":"云吸猫",
  "/gakki":"云吸gakki",
  "/10":"云吸十元",
  "/bird":"云吸飞鸟",
  "/waifu":"云吸二次元老婆",
  "/image":"獭獭传图",
  "/comment":"给作者留言",
  "/about":"关于此项目",
#  "/donate":"援助作者",
  "/random":"掷骰子",
  "/chp":"彩虹屁",
  "/anime":"以图搜番（\"/anime 图片\"）",
  "/gif":"生成沙雕图（\"/gif help\"）",
  "/dice":"DnD掷骰子（\"/dice 3d12\"）",
  "/pixiv":"Pixiv相关功能（\"/pixiv help\"）",
  # "/music":"网易云音乐搜索（\"/music 届不到的恋\"）",
  "/duilian":"对联（\"/duilian 稻花香里说丰年\"）",
  #"/tex":"生成tex图片（\"/tex e^{\\pi i}+1=0\"）",
  "/gate":"挖宝选门（\"/gate 3\"）",
  "/search":"查询物品(\"/search 神龙\")",
  "/weather":"天气信息（快捷命令\"/fog\",\"/heat_wave\",\"/thunder\",\"/kx\"）",
  "/fsx":"副属性计算（\"/fsx 直击\"）",
  "/dps":"DPS排名（\"/dps 8s 骑士\"）",
  "/raid":"零式英雄榜（\"/raid 蓝色裂痕 萌芽池\"）",
  "/quest":"任务查询(\"/quest 狂乱前奏\")",
  "/nuannuan":"本周金蝶暖暖作业",
  "/hso":"好色哦",
  "/bot":"机器人相关功能",
  #"/ifttt":"IFTTT推送系统",
  "/akhr":"罗德岛公开招募",
  #"/share":"发送微博分享",
  # "/trash":"你是什么垃圾？",
  #"/shorten":"微博短链",
  "/luck":"",
  "/mxh":"梅溪湖cp短打生成器（\"/mxh 海德林 佐迪亚克\"）",
  "/hh":"光之收藏家幻化推荐",
  "/treasure":"宝图搜寻",
  "/tataru":"",
  "/turnip":"",
  "/market":"",
  "/ofish":""
}
  # "/joke":"讽刺笑话（\"/joke 996|强东|建设一流公司|程序员|公司\"）",

commands_title = {
  "FF14相关功能":" ",
  "/ofish":"获取最近海钓航班",
  "/market": '交易板数据("/market item 2级刚力之幻药")',
  "/treasure":"G12藏宝图查询|别名 /挖宝,/宝图",
  "副属性计算":"/暴击、/直击、/信念、/坚韧、/咏速、/技速",
  "/hh":"查看光之收藏家的幻化(帮助信息：/hh help,别名：/幻化)",
  "/nuannuan":"本周金蝶暖暖作业",
  "/dps":"查询DPS排名(帮助信息：/dps help)",
  "/raid":"查询零式英雄榜（\"/raid ID 服务器\")",
  "/search":"在最终幻想XIV中查询物品 ",
  "/quest":"任务查询(eg:/quest 暗影之逆焰)",
  "/weather":"天气信息（\"/强风\",\"/暴雪\"）",
  "/gate":"玄学挖宝选门（\"/gate 3\"）",
  "查看云吸图功能":"/help img || 查看其他功能: /help other",
  "/group_help":"复读机与自定义回复等"
}

commands_img = {
  "云吸图相关功能":" ",
  "/cat":"云吸猫 || /bird: 云吸飞鸟",
  "/gakki":"云吸gakkii || /10:云吸10",
  "/hso":"禁忌!-/hso ff14",
  "/pixiv":"Pixiv(详情请输入\"/pixiv help\")"
}

commands_other = {
  "其他相关功能":" ",
  "/mxh":"CP短打生成器",
  "/动图":"生成沙雕图,详情查看塔塔露帮助文档",
  "/random":"掷骰子 || /random [物品] 99 对[物品]掷骰子范围1-99",
  "/anime":"以图搜番（\"/anime 图片\"）",
  "/comment":"留言给开发者 || /group_help:群功能",
  "/akhr":"罗德岛公开招募",
  "/luck":"浅草寺求签",
  "/turnip": "动物森友会大头菜价格预测"
}

group_commands = {
  "/group":"群相关功能控制(订阅星期一的丰满)",
  "/welcome":"设置欢迎语",
  "/custom_reply":"添加自定义命令",
  "/repeat_ban":"复读姬口球系统",
  "/repeat":"开启复读姬系统",
  #"/left_reply":"聊天限额剩余情况",
  "/ban":"投票禁言",
  "/revenge":"复仇",
  "/vote":"投票系统",
  "/weibo":"微博订阅系统",
  #"/live":"直播订阅系统",
  "/command":"群功能停用/启用",
  "/lottery":"抽奖",
 # "/hunt":"狩猎",
}

alter_commands = {
  "/pzz":"/weather 优雷卡常风之地 强风",
  "/blizzard":"/weather 优雷卡恒冰之地 暴雪",
  "/kx":"/weather 优雷卡恒冰之地 暴雪",
  "/fog":"/weather 优雷卡恒冰之地 薄雾",
  "/thunder":"/weather 优雷卡恒冰之地 打雷",
  "/heat_wave":"/weather 优雷卡恒冰之地 热风",
  "/register_group":"/group register",
  "/welcome_demo":"/welcome demo",
  "/set_welcome_msg":"/welcome set",
  "/add_custom_reply list":"/custom_reply list",
  "/add_custom_reply":"/custom_reply add",
  "/del_custom_reply":"/custom_reply del",
  "/set_repeat_ban":"/repeat_ban set",
  "/disable_repeat_ban":"/repeat_ban disable",
  "/set_left_reply_cnt":"/left_reply set",
  "/set_ban":"/ban set",
  "/revenge_confirm":"/revenge confirm",
  "/nn":"/nuannuan",
  "/huntc":"/hunt check",
  "/huntl":"/hunt list cd",
  "/幻化":"/hh",
  "/咏速":"/fsx 速度",
  "/技速":"/fsx 速度",
  "/暴击":"/fsx 暴击",
  "/信念":"/fsx 信念",
  "/坚韧":"/fsx 坚韧",
  "/直击":"/fsx 直击",
  "/宝图":"/treasure",
  "/挖宝":"/treasure",
  "/大头菜":"/turnip",
  "/mitem":"/market item",
  "/海钓": "/ofish",
}
